# Bonus Projet  Machine Learning

# _____________________________________________________________________

### Presenter par : 

##### Ababacar Charles Gueye

##### Serigne Malick Kone

##### Djiga Salane

# _____________________________________________________________________

### importation des module et modele

# _____________________________________________________________________

##### Sklearn : en 1er lieu o import sklearn qui nous permet  d'acceder a sciki-learn

##### numpy : nous faclitera l'utilisation des list(tableau)


##### time : nouspermetra de mesurer la durree de l'entrainemet du model


In [1]:
from time import time
import sklearn
import numpy as np

##### KNeighborsClassifier : est un model de classifiation(Ce pendant pour ameliorer le model n peut sur les super param n_neighbors)

In [2]:
from sklearn.neighbors import KNeighborsClassifier

#### ===> ici on enregistre les donnes d'entrainement i.e(X,y)

In [3]:

X=np.array([[1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
        [1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1],
        [1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1],
        [1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1],
        [0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1],
        [1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1],
        [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1],
        [1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0],
        [1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1],
        [1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1]
        ])
y=np.array(range(10)).reshape(10,1)

X,y

(array([[1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
        [1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1],
        [1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1],
        [1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1],
        [0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1],
        [1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1],
        [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1],
        [1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0],
        [1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1],
        [1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1]]),
 array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]))

#### ici on creer les donees de test (X_test , Y_test): car il nest pas conseiller de tester le model avec des donnees qu'il a deja  connu i.e(X,y)

In [4]:
X_test=np.array([[1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
        [1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1],
        [1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1],
        [1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1],
        [0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1],
        [1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1],
        [1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1],
        [1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0],
        [1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1],
        [1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1]
        ])
y_test=np.array(range(10)).reshape(10,1)
y_test[1]=0
y_test[9]=8

In [5]:
print("Training KNeighborsClassifier...")
tic = time()
model = KNeighborsClassifier(n_neighbors=1)
model.fit(X, y)
print(f"le test a durée {time() - tic:.3f}s")
print(f"le score de la test est : {model.score(X_test, y_test)*100:.2f}%")

Training KNeighborsClassifier...
le test a durée 0.014s
le score de la test est : 80.00%


C:\Users\JERRY\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [6]:
model.predict(X_test)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Faisons la meme chose mais avec svm cette fois si

In [9]:
from sklearn import svm


In [35]:
print("Training de svm.SVR...")
tic = time()
model = svm.SVR(gamma=0.1,C=49)
model.fit(X, y)

print(f"le test a durée {time() - tic:.3f}s")
print(f"le score de la test est : {model.score(X_test, y_test)*100:.2f}%")

Training de svm.SVR...
le test a durée 0.002s
le score de la test est : 89.23%


C:\Users\JERRY\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


#### _validate_for_predict : ne retur pas la valeur predict mais l'entree qui correspond au plus a la valeur predict

In [36]:
res=model._validate_for_predict([[1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1]])
res

array([[1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1.]])

In [37]:
res=model.predict([[1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1]])

##### Avec svm les valeur  predict peuvent ne pas faire partie des y_train

##### Ce qui n est pas le cas avec KNeighborsClassifier


In [38]:
res

array([-0.14505784])

#### le deal est d'arrondire le resultat avec la fonction  suivante

In [53]:
def roundList(tab):
    j=0
    tab2=tab
    for i in tab2:
        tab2[j]=round(i)
        j+=1
    return tab2

In [57]:
res=model.predict(X_test)

print("resulat non arrondie \n",res,"\n")
print("resulat arrondie \n",roundList(res),"\n")

resulat non arrondie 
 [0.1002775  0.42568959 2.10008397 3.09978633 4.10005845 5.10004344
 3.0780336  6.89951688 7.90029525 8.22153719] 

resulat arrondie 
 [0. 0. 2. 3. 4. 5. 3. 7. 8. 8.] 

